"""Add indexes to Like table

Revision ID: 22ccccf71776
Revises: 7c72ca518ac4
Create Date: 2025-06-18 00:48:48.456418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22ccccf71776'
down_revision = '7c72ca518ac4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('like', schema=None) as batch_op:
        batch_op.create_index('ix_like_post_id', ['post_id'], unique=False)
        batch_op.create_index('ix_like_user_id', ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('like', schema=None) as batch_op:
        batch_op.drop_index('ix_like_user_id')
        batch_op.drop_index('ix_like_post_id')

    # ### end Alembic commands ###
