"""Add image_file to Post

Revision ID: 879866bfed15
Revises: 9516c867610b
Create Date: 2025-04-25 13:14:07.435930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '879866bfed15'
down_revision = '9516c867610b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_file', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('image_file')

    # ### end Alembic commands ###
